# base/kustomization.yaml
configMapGenerator:
- name: my-configmap  # Name of the ConfigMap
  literals:
  - key1=value1       # Key-value pairs
  - key2=value2
# base/kustomization.yaml
secretGenerator:
- name: my-secret     # Name of the Secret
  literals:
  - username=admin    # Key-value pairs; consider external management for real secrets
  - password=s3cr3t
